/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.syntio.beam.models;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class DeliveryMethod extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8572967207546772368L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeliveryMethod\",\"namespace\":\"net.syntio.beam.models\",\"fields\":[{\"name\":\"DeliveryMethodID\",\"type\":\"int\"},{\"name\":\"DeliveryMethodLastValidFrom\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"DeliveryMethodLastValidTo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"DeliveryMethodName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeliveryMethod> ENCODER =
      new BinaryMessageEncoder<DeliveryMethod>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeliveryMethod> DECODER =
      new BinaryMessageDecoder<DeliveryMethod>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<DeliveryMethod> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<DeliveryMethod> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeliveryMethod>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this DeliveryMethod to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a DeliveryMethod from a ByteBuffer. */
  public static DeliveryMethod fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int DeliveryMethodID;
  @Deprecated public java.lang.String DeliveryMethodLastValidFrom;
  @Deprecated public java.lang.String DeliveryMethodLastValidTo;
  @Deprecated public java.lang.String DeliveryMethodName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeliveryMethod() {}

  /**
   * All-args constructor.
   * @param DeliveryMethodID The new value for DeliveryMethodID
   * @param DeliveryMethodLastValidFrom The new value for DeliveryMethodLastValidFrom
   * @param DeliveryMethodLastValidTo The new value for DeliveryMethodLastValidTo
   * @param DeliveryMethodName The new value for DeliveryMethodName
   */
  public DeliveryMethod(java.lang.Integer DeliveryMethodID, java.lang.String DeliveryMethodLastValidFrom, java.lang.String DeliveryMethodLastValidTo, java.lang.String DeliveryMethodName) {
    this.DeliveryMethodID = DeliveryMethodID;
    this.DeliveryMethodLastValidFrom = DeliveryMethodLastValidFrom;
    this.DeliveryMethodLastValidTo = DeliveryMethodLastValidTo;
    this.DeliveryMethodName = DeliveryMethodName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return DeliveryMethodID;
    case 1: return DeliveryMethodLastValidFrom;
    case 2: return DeliveryMethodLastValidTo;
    case 3: return DeliveryMethodName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: DeliveryMethodID = (java.lang.Integer)value$; break;
    case 1: DeliveryMethodLastValidFrom = (java.lang.String)value$; break;
    case 2: DeliveryMethodLastValidTo = (java.lang.String)value$; break;
    case 3: DeliveryMethodName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'DeliveryMethodID' field.
   * @return The value of the 'DeliveryMethodID' field.
   */
  public java.lang.Integer getDeliveryMethodID() {
    return DeliveryMethodID;
  }

  /**
   * Sets the value of the 'DeliveryMethodID' field.
   * @param value the value to set.
   */
  public void setDeliveryMethodID(java.lang.Integer value) {
    this.DeliveryMethodID = value;
  }

  /**
   * Gets the value of the 'DeliveryMethodLastValidFrom' field.
   * @return The value of the 'DeliveryMethodLastValidFrom' field.
   */
  public java.lang.String getDeliveryMethodLastValidFrom() {
    return DeliveryMethodLastValidFrom;
  }

  /**
   * Sets the value of the 'DeliveryMethodLastValidFrom' field.
   * @param value the value to set.
   */
  public void setDeliveryMethodLastValidFrom(java.lang.String value) {
    this.DeliveryMethodLastValidFrom = value;
  }

  /**
   * Gets the value of the 'DeliveryMethodLastValidTo' field.
   * @return The value of the 'DeliveryMethodLastValidTo' field.
   */
  public java.lang.String getDeliveryMethodLastValidTo() {
    return DeliveryMethodLastValidTo;
  }

  /**
   * Sets the value of the 'DeliveryMethodLastValidTo' field.
   * @param value the value to set.
   */
  public void setDeliveryMethodLastValidTo(java.lang.String value) {
    this.DeliveryMethodLastValidTo = value;
  }

  /**
   * Gets the value of the 'DeliveryMethodName' field.
   * @return The value of the 'DeliveryMethodName' field.
   */
  public java.lang.String getDeliveryMethodName() {
    return DeliveryMethodName;
  }

  /**
   * Sets the value of the 'DeliveryMethodName' field.
   * @param value the value to set.
   */
  public void setDeliveryMethodName(java.lang.String value) {
    this.DeliveryMethodName = value;
  }

  /**
   * Creates a new DeliveryMethod RecordBuilder.
   * @return A new DeliveryMethod RecordBuilder
   */
  public static net.syntio.beam.models.DeliveryMethod.Builder newBuilder() {
    return new net.syntio.beam.models.DeliveryMethod.Builder();
  }

  /**
   * Creates a new DeliveryMethod RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeliveryMethod RecordBuilder
   */
  public static net.syntio.beam.models.DeliveryMethod.Builder newBuilder(net.syntio.beam.models.DeliveryMethod.Builder other) {
    return new net.syntio.beam.models.DeliveryMethod.Builder(other);
  }

  /**
   * Creates a new DeliveryMethod RecordBuilder by copying an existing DeliveryMethod instance.
   * @param other The existing instance to copy.
   * @return A new DeliveryMethod RecordBuilder
   */
  public static net.syntio.beam.models.DeliveryMethod.Builder newBuilder(net.syntio.beam.models.DeliveryMethod other) {
    return new net.syntio.beam.models.DeliveryMethod.Builder(other);
  }

  /**
   * RecordBuilder for DeliveryMethod instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeliveryMethod>
    implements org.apache.avro.data.RecordBuilder<DeliveryMethod> {

    private int DeliveryMethodID;
    private java.lang.String DeliveryMethodLastValidFrom;
    private java.lang.String DeliveryMethodLastValidTo;
    private java.lang.String DeliveryMethodName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.syntio.beam.models.DeliveryMethod.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.DeliveryMethodID)) {
        this.DeliveryMethodID = data().deepCopy(fields()[0].schema(), other.DeliveryMethodID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DeliveryMethodLastValidFrom)) {
        this.DeliveryMethodLastValidFrom = data().deepCopy(fields()[1].schema(), other.DeliveryMethodLastValidFrom);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DeliveryMethodLastValidTo)) {
        this.DeliveryMethodLastValidTo = data().deepCopy(fields()[2].schema(), other.DeliveryMethodLastValidTo);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DeliveryMethodName)) {
        this.DeliveryMethodName = data().deepCopy(fields()[3].schema(), other.DeliveryMethodName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing DeliveryMethod instance
     * @param other The existing instance to copy.
     */
    private Builder(net.syntio.beam.models.DeliveryMethod other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.DeliveryMethodID)) {
        this.DeliveryMethodID = data().deepCopy(fields()[0].schema(), other.DeliveryMethodID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DeliveryMethodLastValidFrom)) {
        this.DeliveryMethodLastValidFrom = data().deepCopy(fields()[1].schema(), other.DeliveryMethodLastValidFrom);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DeliveryMethodLastValidTo)) {
        this.DeliveryMethodLastValidTo = data().deepCopy(fields()[2].schema(), other.DeliveryMethodLastValidTo);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DeliveryMethodName)) {
        this.DeliveryMethodName = data().deepCopy(fields()[3].schema(), other.DeliveryMethodName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'DeliveryMethodID' field.
      * @return The value.
      */
    public java.lang.Integer getDeliveryMethodID() {
      return DeliveryMethodID;
    }

    /**
      * Sets the value of the 'DeliveryMethodID' field.
      * @param value The value of 'DeliveryMethodID'.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder setDeliveryMethodID(int value) {
      validate(fields()[0], value);
      this.DeliveryMethodID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryMethodID' field has been set.
      * @return True if the 'DeliveryMethodID' field has been set, false otherwise.
      */
    public boolean hasDeliveryMethodID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'DeliveryMethodID' field.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder clearDeliveryMethodID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeliveryMethodLastValidFrom' field.
      * @return The value.
      */
    public java.lang.String getDeliveryMethodLastValidFrom() {
      return DeliveryMethodLastValidFrom;
    }

    /**
      * Sets the value of the 'DeliveryMethodLastValidFrom' field.
      * @param value The value of 'DeliveryMethodLastValidFrom'.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder setDeliveryMethodLastValidFrom(java.lang.String value) {
      validate(fields()[1], value);
      this.DeliveryMethodLastValidFrom = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryMethodLastValidFrom' field has been set.
      * @return True if the 'DeliveryMethodLastValidFrom' field has been set, false otherwise.
      */
    public boolean hasDeliveryMethodLastValidFrom() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'DeliveryMethodLastValidFrom' field.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder clearDeliveryMethodLastValidFrom() {
      DeliveryMethodLastValidFrom = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeliveryMethodLastValidTo' field.
      * @return The value.
      */
    public java.lang.String getDeliveryMethodLastValidTo() {
      return DeliveryMethodLastValidTo;
    }

    /**
      * Sets the value of the 'DeliveryMethodLastValidTo' field.
      * @param value The value of 'DeliveryMethodLastValidTo'.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder setDeliveryMethodLastValidTo(java.lang.String value) {
      validate(fields()[2], value);
      this.DeliveryMethodLastValidTo = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryMethodLastValidTo' field has been set.
      * @return True if the 'DeliveryMethodLastValidTo' field has been set, false otherwise.
      */
    public boolean hasDeliveryMethodLastValidTo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'DeliveryMethodLastValidTo' field.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder clearDeliveryMethodLastValidTo() {
      DeliveryMethodLastValidTo = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'DeliveryMethodName' field.
      * @return The value.
      */
    public java.lang.String getDeliveryMethodName() {
      return DeliveryMethodName;
    }

    /**
      * Sets the value of the 'DeliveryMethodName' field.
      * @param value The value of 'DeliveryMethodName'.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder setDeliveryMethodName(java.lang.String value) {
      validate(fields()[3], value);
      this.DeliveryMethodName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'DeliveryMethodName' field has been set.
      * @return True if the 'DeliveryMethodName' field has been set, false otherwise.
      */
    public boolean hasDeliveryMethodName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'DeliveryMethodName' field.
      * @return This builder.
      */
    public net.syntio.beam.models.DeliveryMethod.Builder clearDeliveryMethodName() {
      DeliveryMethodName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeliveryMethod build() {
      try {
        DeliveryMethod record = new DeliveryMethod();
        record.DeliveryMethodID = fieldSetFlags()[0] ? this.DeliveryMethodID : (java.lang.Integer) defaultValue(fields()[0]);
        record.DeliveryMethodLastValidFrom = fieldSetFlags()[1] ? this.DeliveryMethodLastValidFrom : (java.lang.String) defaultValue(fields()[1]);
        record.DeliveryMethodLastValidTo = fieldSetFlags()[2] ? this.DeliveryMethodLastValidTo : (java.lang.String) defaultValue(fields()[2]);
        record.DeliveryMethodName = fieldSetFlags()[3] ? this.DeliveryMethodName : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeliveryMethod>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeliveryMethod>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeliveryMethod>
    READER$ = (org.apache.avro.io.DatumReader<DeliveryMethod>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
